serdev-objs := core.o

obj-$(CONFIG_SERIAL_DEV_BUS) += serdev.o

obj-$(CONFIG_SERIAL_DEV_CTRL_TTYPORT) += serdev-ttyport.o

obj-$(CONFIG_SERIAL_DEV_CTRL_TTYDEV) += serdev-ttydev.o

obj-$(CONFIG_SERIAL_DEV_CTRL_TTYDEV) += test_platform.o
